<div id="lista" class="lista">
  <ul>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
    <li>LLALAL</li>
  </ul>
</div>

